In [1]:
import numpy as np
import time

In [2]:
# Excecution verification
li1 = list(range(10000000))
start = time.time()
sqr = [x**2 for x in li1]
end = time.time()
x1 = end - start
print(x1)

arr = np.array(range(10000000))
start = time.time()
sq2 = arr**2
end = time.time()
x2 = end - start
print(x2)

0.8703162670135498
0.023998737335205078


In [3]:
# Creating Numpy Array - 0d and 1d
print("0 D array")
zerod = np.array(45)
print(zerod)
print(zerod.ndim)
print(zerod.shape)

print("1 D array")
arr1 = np.array([1,2,3,4,4,5,76,7,9])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)

0 D array
45
0
()
1 D array
[ 1  2  3  4  4  5 76  7  9]
<class 'numpy.ndarray'>
int64
1
(9,)


In [4]:
# creating 2d array
print("2d array")
li = [[1,2,3],[3,4,5],[2,5,7]]
td = np.array(li)
print(td)
print(f"Shape of the array : {td.shape}")
print(f"D type of the array : {td.dtype}")
print(f"Dimentions of the array : {td.ndim}")
print(f"Size of the array : {td.size}")

2d array
[[1 2 3]
 [3 4 5]
 [2 5 7]]
Shape of the array : (3, 3)
D type of the array : int64
Dimentions of the array : 2
Size of the array : 9


In [5]:
# Creating arrays using inbuilt functions
a1 = np.zeros((3,2))
print("zeros")
print(a1)
a2 = np.ones((2,3,2))
print("ones")
print(a2)
a3 = np.full((3,4),7)
print("Fill element full")
print(a3)
a4 = np.eye(3)
print("Identity")
print(a4)
a5 = np.diag([1,5,3,2])
print("Diagonal")
print(a5)
a6 = np.arange(1,10,2)
print("Arrange")
print(a6)
a7 = np.linspace(0,5,3)
print("Evenly spaced")
print(a7)
a8 = np.empty((2,2))
print("Empty")
print(a8)

zeros
[[0. 0.]
 [0. 0.]
 [0. 0.]]
ones
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
Fill element full
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal
[[1 0 0 0]
 [0 5 0 0]
 [0 0 3 0]
 [0 0 0 2]]
Arrange
[1 3 5 7 9]
Evenly spaced
[0.  2.5 5. ]
Empty
[[4.9e-324 2.5e-323]
 [1.5e-323 9.9e-324]]


In [6]:
# Data types in np arrays
b1 = np.array([1,2,3,4],dtype = 'int64')
print(b1,b1.dtype)
b1 = b1.astype('float64')
print(b1,b1.dtype)
b2 = np.array([0,1,0,1])
b2 = b2.astype('bool')
print(b2,b2.dtype)
b3 = np.arange(1,10)
print(b3,b3.dtype)
b3 = b3.astype('str')
print(b3,b3.dtype)

[1 2 3 4] int64
[1. 2. 3. 4.] float64
[False  True False  True] bool
[1 2 3 4 5 6 7 8 9] int64
['1' '2' '3' '4' '5' '6' '7' '8' '9'] <U21


In [7]:
# Indexing and Slicing 
# 1d array
print("1D array")
a = np.array([1,2,3,4,5,6])
print(a)
print(a[0])
print(a[1:4])
print(a[-4:-2])
print(a[-2:-4:-1])

print("2D array")
# 2d array
b = np.array([[4,2,5],[1,4,2],[7,3,9]])
print(b)
print(b[0,1])
print(b[1,])
print(b[2,-1])
print(b[:,2])
print(b[0:2,1:3])

1D array
[1 2 3 4 5 6]
1
[2 3 4]
[3 4]
[5 4]
2D array
[[4 2 5]
 [1 4 2]
 [7 3 9]]
2
[1 4 2]
9
[5 2 9]
[[2 5]
 [4 2]]


In [8]:
# boolean indexing
import random as rnd
marks = rnd.sample(range(1,100),20)
print(marks)
marks = np.array(marks)
students = marks[marks>45]
print(students)

[19, 11, 48, 34, 72, 20, 21, 44, 9, 77, 15, 54, 14, 42, 16, 50, 93, 33, 78, 58]
[48 72 77 54 50 93 78 58]


In [9]:
# Fancy Indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[[0,2],[1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 8]


In [10]:
# Reshape and manipulation
arr = np.array(range(1,13))
print(arr)
print(arr.ndim)
print(arr.shape)
print()
arr = arr.reshape(6,2)
print(arr)
print(arr.ndim)
print(arr.shape)
print()
arr = arr.reshape(3,4)
print(arr)
print(arr.ndim)
print(arr.shape)
print()
arr = arr.reshape(3,2,2)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.T) # For transpose

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2
(6, 2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)
[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


In [11]:
# Flattening Ravel
arr = arr.flatten()
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [12]:
arr = arr.reshape(2,3,2)
# arr = arr.reshape(-1) can also be used for flattening
arr = arr.ravel()
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [13]:
a = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[7,8]]])
print(a)
print(a.ndim)
print(a.shape)
print(a[0,1,-1])
print(a[1,1,0])

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [7 8]]]
3
(2, 3, 2)
3
5
