In [1]:
import numpy as np

In [2]:
# Vectorization and Broadcasting
a = np.array([1,2,3,4,5])
print(a**2)
print(a+2)

[ 1  4  9 16 25]
[3 4 5 6 7]


In [3]:
# normalisation
import random as rnd
a = np.array(rnd.sample(range(1,100),20))
print(a)
mean = a.mean()
std = a.std()
a = a-mean
a = a/std
print(a)

[ 4 65 99 67 75  2 19 53 15 77 44 61 82 38 46 85 89 92 74 58]
[-1.86390873  0.2712731   1.46137445  0.34127906  0.62130291 -1.93391469
 -1.33886402 -0.14876267 -1.47887594  0.69130887 -0.4637895   0.13126118
  0.86632378 -0.67380738 -0.39378353  0.97133272  1.11134464  1.21635358
  0.58629993  0.02625224]


In [4]:
# Math functions
arr = np.array([43,57,28,91,74])
print(f"sum = {arr.sum()}")
print(f"product = {arr.prod()}")
print(f"Mean = {arr.mean()}")
print(f"Median = {np.median(arr)}")
print(f"Max = {arr.max()} and min = {arr.min()}")
print(f"Standard deviation = {arr.std()}")
print(f"Variance = {np.var(arr)}")

sum = 293
product = 462140952
Mean = 58.6
Median = 57.0
Max = 91 and min = 28
Standard deviation = 22.222511109233356
Variance = 493.84


In [5]:
# other functions
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sort(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[6.55743852 7.54983444 5.29150262 9.53939201 8.60232527]
[3.76120012 4.04305127 3.33220451 4.51085951 4.30406509]
[4.72783947e+18 5.68572000e+24 1.44625706e+12 3.31740010e+39
 1.37338298e+32]
[28 43 57 74 91]
[-0.83177474  0.43616476  0.27090579  0.10598751 -0.98514626]
[ 0.5551133   0.89986683 -0.96260587 -0.99436746  0.17171734]
[-1.49838734  0.48469923 -0.2814296  -0.10658787 -5.73702254]


In [8]:
# Joining and splitting
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.split(arr,3))
print(np.array_split(arr,(4,7)))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9])]
